#include "CBaseItem.h"
#include "Components/BoxComponent.h"
#include "Components/SphereComponent.h"
#include "CInventoryComponent.h"
#include "Kismet/GameplayStatics.h"
#include "CPlayer.h"

// ğŸ”¹ ê¸°ë³¸ ìƒì„±ì
ACBaseItem::ACBaseItem() :
    bCanUse(false),
    bConsumable(false)
{
    PrimaryActorTick.bCanEverTick = false;

    // âœ… RootComponent ì„¤ì • (í•„ìš”í•œ ê²½ìš°ë§Œ)
    if (!RootComponent)
    {
        RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
    }

    // ğŸš€ InteractableCollisionì„ ì¤‘ë³µ ìƒì„±í•˜ì§€ ì•Šê³ , ë¶€ëª¨ í´ë˜ìŠ¤ì˜ ê²ƒì„ í™œìš©
    if (InteractableCollision) // ë¶€ëª¨ í´ë˜ìŠ¤ì—ì„œ ì´ë¯¸ ì¡´ì¬í•¨
    {
        InteractableCollision->SetupAttachment(RootComponent);  // ë¶€ëª¨ í´ë˜ìŠ¤ì™€ ì¶©ëŒí•˜ì§€ ì•Šë„ë¡ ë‹¤ì‹œ ì„¤ì • ê°€ëŠ¥
        InteractableCollision->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
        InteractableCollision->SetGenerateOverlapEvents(true);
    }

    // âœ… StaticMesh ìƒì„± ë° RootComponentì— ë¶€ì°©
    StaticMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("StaticMesh"));
    StaticMesh->SetupAttachment(RootComponent);
    StaticMesh->SetCollisionProfileName(TEXT("BlockAllDynamic"));
    StaticMesh->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    StaticMesh->SetCollisionResponseToAllChannels(ECR_Block);

    // âœ… ì•„ì´í…œ ì†ì„± ì´ˆê¸°í™”
    KeyPressedSound = nullptr;
    UseSound = nullptr;
    ItemIcon = nullptr;
}

// ğŸ”¹ ì¸ë²¤í† ë¦¬ì— ì•„ì´í…œ ì¶”ê°€
bool ACBaseItem::PutIntoInventory(AActor* PlayerHavingInventory)
{
    ACPlayer* CPlayer = Cast<ACPlayer>(PlayerHavingInventory);
    if (CPlayer)
    {
        UCInventoryComponent* Inventory = CPlayer->FindComponentByClass<UCInventoryComponent>();
        if (Inventory)
        {
            bool bAdded = Inventory->AddToInventory(GetItemType());

            // âœ… ë””ë²„ê·¸ ë©”ì‹œì§€ ì¶”ê°€
            FString ItemName = UEnum::GetValueAsString(GetItemType());
            GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Green, FString::Printf(TEXT("ì¸ë²¤í† ë¦¬ì— ì¶”ê°€ë¨: %s"), *ItemName));
            if (bAdded)
            {
                if (KeyPressedSound)
                {
                    UGameplayStatics::PlaySoundAtLocation(this, KeyPressedSound, GetActorLocation());
                }
                UE_LOG(LogTemp, Warning, TEXT("ì•„ì´í…œ %d ì¸ë²¤í† ë¦¬ì— ì¶”ê°€ë¨!"), static_cast<int32>(GetItemType()));

                Inventory->PrintInventory(); // ğŸ”¹ ì¸ë²¤í† ë¦¬ ìƒíƒœ ì¶œë ¥

                // ì•„ì´í…œì„ ì¸ë²¤í† ë¦¬ì— ì¶”ê°€í–ˆìœ¼ë©´, ì›”ë“œì—ì„œ ì œê±°
                Destroy();
            }

            return bAdded;  // **returnì„ ìµœì¢…ì ìœ¼ë¡œ í•œ ë²ˆë§Œ ì‚¬ìš©**
        }
    }
    return false; // í”Œë ˆì´ì–´ë‚˜ ì¸ë²¤í† ë¦¬ë¥¼ ì°¾ì§€ ëª»í•˜ë©´ false ë°˜í™˜
}

// ğŸ”¹ ì•„ì´í…œ ì‚¬ìš©
void ACBaseItem::Use(AActor* Target)
{
    if (UseSound)
    {
        UGameplayStatics::PlaySoundAtLocation(this, UseSound, GetActorLocation());
    }

    if (bConsumable)
    {
        ACPlayer* Player = Cast<ACPlayer>(Target);
        if (Player)
        {
            UCInventoryComponent* Inventory = Player->FindComponentByClass<UCInventoryComponent>();
            if (Inventory)
            {
                Inventory->RemoveItem(GetItemType());
            }
        }
    }
}

// ğŸ”¹ ì•„ì´í…œ íƒ€ì… ë°˜í™˜
EItemType ACBaseItem::GetItemType() const
{
    return ItemType;
}

void ACBaseItem::BeginPlay()
{
    Super::BeginPlay();

    // âœ… ì˜¤ë²„ë© ì´ë²¤íŠ¸ ë°”ì¸ë”©
    if (InteractableCollision)
    {
        InteractableCollision->OnComponentBeginOverlap.AddDynamic(this, &ACBaseItem::OnOverlap);
    }
}

void ACBaseItem::OnOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    ACPlayer* Player = Cast<ACPlayer>(OtherActor);
    if (Player)
    {
        GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Yellow, TEXT("ì•„ì´í…œ ê°ì§€ë¨!"));

        // âœ… ì•„ì´í…œì„ ìë™ìœ¼ë¡œ ì¸ë²¤í† ë¦¬ì— ì¶”ê°€
       /* PutIntoInventory(Player);*/
    }
}